/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ASUS
 */
public class calgui extends javax.swing.JFrame {

   String angka;
   double jumlah,bil1,bil2;
   int pilih;
    public calgui() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layar = new javax.swing.JTextField();
        BtnAngka7 = new javax.swing.JButton();
        BtnAngka8 = new javax.swing.JButton();
        BtnAngka9 = new javax.swing.JButton();
        BtnAngka4 = new javax.swing.JButton();
        BtnAngka5 = new javax.swing.JButton();
        BtnAngka6 = new javax.swing.JButton();
        BtnAngka1 = new javax.swing.JButton();
        BtnAngka2 = new javax.swing.JButton();
        BtnAngka0 = new javax.swing.JButton();
        BtnAngka3 = new javax.swing.JButton();
        Btnkoma = new javax.swing.JButton();
        Btnbagi = new javax.swing.JButton();
        Btnkali = new javax.swing.JButton();
        Btnkurang = new javax.swing.JButton();
        Btntambah = new javax.swing.JButton();
        Btnsamadengan = new javax.swing.JButton();
        Btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("kalkulator");
        setResizable(false);

        layar.setEditable(false);
        layar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        layar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layarActionPerformed(evt);
            }
        });

        BtnAngka7.setText("7");
        BtnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka7ActionPerformed(evt);
            }
        });

        BtnAngka8.setText("8");
        BtnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka8ActionPerformed(evt);
            }
        });

        BtnAngka9.setText("9");
        BtnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka9ActionPerformed(evt);
            }
        });

        BtnAngka4.setText("4");
        BtnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka4ActionPerformed(evt);
            }
        });

        BtnAngka5.setText("5");
        BtnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka5ActionPerformed(evt);
            }
        });

        BtnAngka6.setText("6");
        BtnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka6ActionPerformed(evt);
            }
        });

        BtnAngka1.setText("1");
        BtnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka1ActionPerformed(evt);
            }
        });

        BtnAngka2.setText("2");
        BtnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka2ActionPerformed(evt);
            }
        });

        BtnAngka0.setText("0");
        BtnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka0ActionPerformed(evt);
            }
        });

        BtnAngka3.setText("3");
        BtnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka3ActionPerformed(evt);
            }
        });

        Btnkoma.setText(",");
        Btnkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkomaActionPerformed(evt);
            }
        });

        Btnbagi.setText("/");
        Btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbagiActionPerformed(evt);
            }
        });

        Btnkali.setText("*");
        Btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkaliActionPerformed(evt);
            }
        });

        Btnkurang.setText("-");
        Btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkurangActionPerformed(evt);
            }
        });

        Btntambah.setText("+");
        Btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntambahActionPerformed(evt);
            }
        });

        Btnsamadengan.setText("=");
        Btnsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsamadenganActionPerformed(evt);
            }
        });

        Btnhapus.setText("c");
        Btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnsamadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btnbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnAngka0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(BtnAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnAngka3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(Btnkoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btnkurang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btnkali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(layar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnkali, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAngka3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAngka0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btnkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Btnsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkomaActionPerformed
        angka += ",";
        layar.setText(angka);
    }//GEN-LAST:event_BtnkomaActionPerformed

    private void layarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layarActionPerformed

    private void BtntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntambahActionPerformed
       bil1=Double.parseDouble(angka);
        layar.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_BtntambahActionPerformed

    private void BtnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka7ActionPerformed
        angka += "7";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka7ActionPerformed

    private void BtnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka8ActionPerformed
        angka += "8";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka8ActionPerformed

    private void BtnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka9ActionPerformed
        angka += "9";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka9ActionPerformed

    private void BtnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka4ActionPerformed
        angka += "4";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka4ActionPerformed

    private void BtnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka5ActionPerformed
        angka += "5";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka5ActionPerformed

    private void BtnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka6ActionPerformed
        angka += "6";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka6ActionPerformed

    private void BtnAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka1ActionPerformed
        angka += "1";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka1ActionPerformed

    private void BtnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka2ActionPerformed
       angka += "2";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka2ActionPerformed

    private void BtnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka3ActionPerformed
        angka += "3";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka3ActionPerformed

    private void BtnAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka0ActionPerformed
        angka += "0";
        layar.setText(angka);
    }//GEN-LAST:event_BtnAngka0ActionPerformed

    private void BtnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbagiActionPerformed
        bil1=Double.parseDouble(angka);
        layar.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_BtnbagiActionPerformed

    private void BtnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkaliActionPerformed
        bil1=Double.parseDouble(angka);
        layar.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_BtnkaliActionPerformed

    private void BtnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkurangActionPerformed
        bil1=Double.parseDouble(angka);
        layar.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_BtnkurangActionPerformed

    private void BtnsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsamadenganActionPerformed
        switch(pilih){
        case 1:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 + bil2;
            angka = Double.toString(jumlah);
            layar.setText(angka);
            break;
        case 2:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 - bil2;
            angka = Double.toString(jumlah);
            layar.setText(angka);
            break;
        case 3:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 * bil2;
            angka = Double.toString(jumlah);
            layar.setText(angka);
            break;
        case 4:
            bil2 = Double.parseDouble(angka);
            jumlah = bil1 / bil2;
            angka = Double.toString(jumlah);
            layar.setText(angka);
            break;
        default:
            break;
            
            }
    }//GEN-LAST:event_BtnsamadenganActionPerformed

    private void BtnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnhapusActionPerformed
        layar.setText("");
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        angka="";
        
    }//GEN-LAST:event_BtnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAngka0;
    private javax.swing.JButton BtnAngka1;
    private javax.swing.JButton BtnAngka2;
    private javax.swing.JButton BtnAngka3;
    private javax.swing.JButton BtnAngka4;
    private javax.swing.JButton BtnAngka5;
    private javax.swing.JButton BtnAngka6;
    private javax.swing.JButton BtnAngka7;
    private javax.swing.JButton BtnAngka8;
    private javax.swing.JButton BtnAngka9;
    private javax.swing.JButton Btnbagi;
    private javax.swing.JButton Btnhapus;
    private javax.swing.JButton Btnkali;
    private javax.swing.JButton Btnkoma;
    private javax.swing.JButton Btnkurang;
    private javax.swing.JButton Btnsamadengan;
    private javax.swing.JButton Btntambah;
    private javax.swing.JTextField layar;
    // End of variables declaration//GEN-END:variables
}
